theme = "nightfox"

[editor]
auto-format = true
line-number = "relative"

[editor.clipboard-provider.custom]
yank = { command = "powershell.exe", args = ["-NoProfile", "-Command", "Get-Clipboard"] }
paste = { command = "win-clip", args = [] }

[keys.normal]
# movement
u = "move_line_up"
e = "move_line_down"
n = "move_char_left"
i = "move_char_right"
y = "move_next_word_start"
Y = "move_next_long_word_start"
o = "move_next_word_end"
O = "move_next_long_word_end"
h = "move_prev_word_start"
H = "move_prev_long_word_start"
j = "find_till_char"
J = "till_prev_char"
C-u = "page_cursor_half_up"
C-e = "page_cursor_half_down"
C-l = "page_up"
C-n = "page_down"

# changes
s = "insert_mode"
S = "insert_at_line_start"
t = "append_mode"
T = "insert_at_line_end"
p = "open_below"
P = "open_above"
z = "undo"
Z = "redo"
c = "yank"
v = "paste_after"
V = "paste_before"
a = "change_selection"
A = ["select_mode", "goto_line_end", "change_selection"]
A-a = "change_selection_noyank"

# selection manipulation
E = "join_selections"
A-E = "join_selections_space"
# x = "select_regex"
# X = "split_selection"
# A-x = "split_selection_on_newline"
# a = "extend_line_below"
# A = "extend_to_line_bounds"
# A-a = "shrink_to_line_bounds"

# search
k = "search_next"
K = "search_prev"

# minor modes
b = "select_mode"

# custom
C-y = ":sh zellij run -fc -- yy"
C-p = ":sh hx-markdown-preview \"%{buffer_name}\""

[keys.select]
u = "extend_visual_line_up"
e = "extend_visual_line_down"
n = "extend_char_left"
i = "extend_char_right"
l = "extend_prev_word_start"
L = "extend_prev_long_word_start"
y = "extend_next_word_start"
Y = "extend_next_long_word_start"
o = "extend_next_word_end"
O = "extend_next_long_word_end"
a = "normal_mode"

c = "yank"

