[language-server.efm]
command = "efm-langserver"

[[language]]
name = "markdown"
language-servers = ["efm","markdown-oxide"]
formatter = { command = "prettier", args = ["--parser", "markdown"] }
auto-format = true

