[language-server.rumdl]
command = "rumdl"
args = ["server"]

[language-server.vscode-eslint-language-server]
command = "vscode-eslint-language-server"
args = ["--stdio"]

[language-server.vscode-eslint-language-server.config]
validate = "on"
run = "onType"
nodePath = ""
problems = { shortenToSingleLine = false }
experimental = { useFlatConfig = true }

[language-server.vscode-eslint-language-server.config.workingDirectory]
mode = "location"

[language-server.efm]
command = "efm-langserver"

[language-server.gopls]
command = "gopls"

[language-server.gopls.config]
gofumpt = true
staticcheck = true

[language-server.gopls.config.analyses]
unusedparams = true
unreachable = true
nilness = true
shadow = true

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }
language-servers = ["gopls"]

[[language]]
name = "javascript"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]
formatter = { command = "npm", args = ["exec", "--", "prettier", "--stdin-filepath", "%{buffer_name}"] }
auto-format = true

[[language]]
name = "markdown"
language-servers = [
  "marksman",
  "rumdl",
]
text-width = 120
soft-wrap = { enable = true, wrap-at-text-width = false, wrap-indicator = "" }
comment-tokens = [
  "-",
  "+",
  "*",
  "1.",
  ">",
  "- [ ]",
]
formatter = { command = "rumdl", args = ["fmt", "--silent", "-"] }
auto-format = true

[[language]]
name = "typescript"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]
formatter = { command = "npm", args = ["exec", "--", "prettier", "--stdin-filepath", "%{buffer_name}"] }
auto-format = true

[[language]]
name = "jsx"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]
formatter = { command = "npm", args = ["exec", "--", "prettier", "--stdin-filepath", "%{buffer_name}"] }
auto-format = true

[[language]]
name = "tsx"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]
formatter = { command = "npm", args = ["exec", "--", "prettier", "--stdin-filepath", "%{buffer_name}"] }
auto-format = true
