[tools]
aws-cli = { version = "latest", symlink_bins = "true" }
cargo-binstall = "latest"
claude = "latest"
go = "latest"
"go:github.com/air-verse/air" = "latest"
"go:github.com/chrishrb/go-grip" = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
"go:github.com/golangci/golangci-lint/cmd/golangci-lint" = "latest"
"go:github.com/mattn/efm-langserver" = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
golangci-lint = "latest"
helix = "latest"
lazygit = "latest"
markdownlint-cli2 = "latest"
neovim = "latest"
node = "lts"
"npm:@openai/codex" = "latest"
"npm:prettier" = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
rust = "latest"
uv = "latest"
yazi = "latest"
zellij = "latest"
